include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - .history/**
  errors:
    todo: ignore
    invalid_assignment: warning
    missing_return: error
    dead_code: info
    comment_references: ignore

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    use_super_parameters: true
    empty_statements: false
    prefer_relative_imports: true
    avoid_type_to_string: true
    avoid_types_as_parameter_names: true
    cancel_subscriptions: true
    comment_references: true

